# Project: ÏîÄ¿3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainf.o file1.o file2.o file3.o
LINKOBJ  = mainf.o file1.o file2.o file3.o
LIBS     = -L"E:/Applications/IDEs/Dev-Cpp/MinGW64/lib" -L"E:/Applications/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/include" -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/include" -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Applications/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainf.o: mainf.cpp
	$(CPP) -c mainf.cpp -o mainf.o $(CXXFLAGS)

file1.o: file1.cpp
	$(CPP) -c file1.cpp -o file1.o $(CXXFLAGS)

file2.o: file2.cpp
	$(CPP) -c file2.cpp -o file2.o $(CXXFLAGS)

file3.o: file3.cpp
	$(CPP) -c file3.cpp -o file3.o $(CXXFLAGS)
